#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$: << "#{File.dirname(__FILE__)}"

require 'open_vz_driver'
require 'open_vz_data'

p 'Hello from one-ovz driver'

driver = OpenNebula::OpenVzDriver.new()
# TODO change DATA to STDIN
data = OpenNebula::OpenVzData.new(DATA)
driver.deploy data

p driver.deploy_id

__END__
<?xml version="1.0" encoding="UTF-8"?>
<TEMPLATE>
  <VMID>
    <![CDATA[24]]>
  </VMID>
</TEMPLATE>
