#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$: << "#{File.dirname(__FILE__)}"
$: << "#{File.dirname(__FILE__)}/../../"

require 'open_vz_driver'

open_vz_data = OpenNebula::OpenVzData.new STDIN
inventory = OpenVZ::Inventory.new
driver = OpenNebula::OpenVzDriver.new

# setup container
ctid = OpenNebula::OpenVzDriver.ctid inventory, open_vz_data.vmid
container = OpenVZ::Container.new(ctid)

# final step
deploy_ctid = driver.deploy open_vz_data, container

begin
  p deploy_ctid
rescue OpenNebula::OpenVzDriver::OpenVzDriverException => e
  p e.message
end
